-- Staging model for dbo.customers
-- Generated by Datarcon on 2026-03-10 17:24:44

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        customer_id,
    first_name,
    last_name,
    email,
    phone,
    region,
    is_active,
    created_at,
    updated_at
    FROM {{ source('mssql_source', 'customers') }}

),

staged AS (

    SELECT
        customer_id,
    first_name,
    last_name,
    email,
    phone,
    region,
    is_active,
    created_at,
    updated_at
    FROM source

)

SELECT * FROM staged
