-- Staging model for dbo.orders
-- Generated by Datarcon on 2026-03-10 17:24:44

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        order_id,
    customer_id,
    order_date,
    total_amount,
    status,
    region,
    created_at
    FROM {{ source('mssql_source', 'orders') }}

),

staged AS (

    SELECT
        order_id,
    customer_id,
    order_date,
    total_amount,
    status,
    region,
    created_at
    FROM source

)

SELECT * FROM staged
