-- Staging model for dbo.products
-- Generated by Datarcon on 2026-03-10 17:24:44

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        product_id,
    name,
    sku,
    category,
    price,
    stock_quantity,
    reorder_level,
    is_active,
    created_at
    FROM {{ source('mssql_source', 'products') }}

),

staged AS (

    SELECT
        product_id,
    name,
    sku,
    category,
    price,
    stock_quantity,
    reorder_level,
    is_active,
    created_at
    FROM source

)

SELECT * FROM staged
