-- Staging model for dbo.order_items
-- Generated by Datarcon on 2026-03-10 17:24:44

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    line_total
    FROM {{ source('mssql_source', 'order_items') }}

),

staged AS (

    SELECT
        item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    line_total
    FROM source

)

SELECT * FROM staged
