-- dbt model generated from stored procedure: dbo.sp_CustomerOrderSummary
-- Generated by Datarcon on 2026-03-10 17:24:55
-- Original procedure translated to databricks SQL


{{ config(
    materialized='view',
    schema='procedures'
) }}

SELECT
        c.customer_id,
        c.first_name || ' ' || c.last_name AS customer_name,
        COUNT(o.order_id) AS total_orders,
        COALESCE(SUM(o.total_amount), 0) AS total_spent,
        MAX(o.order_date) AS last_order_date
    FROM {{ ref('stg_customers') }} c
    LEFT JOIN {{ ref('stg_orders') }} o ON c.customer_id = o.customer_id
    WHERE c.is_active = TRUE
    GROUP BY c.customer_id, c.first_name, c.last_name
    ORDER BY total_spent DESC
