-- dbt model generated from stored procedure: dbo.sp_SalesByRegion
-- Generated by Datarcon on 2026-03-10 17:24:55
-- Original procedure translated to databricks SQL


{{ config(
    materialized='view',
    schema='procedures'
) }}

IF DATEADD(YEAR, -1, CURRENT_TIMESTAMP()) IS NULL 
    IF CURRENT_TIMESTAMP() IS NULL 

    SELECT
        region,
        COUNT(order_id) AS order_count,
        SUM(total_amount) AS total_sales,
        AVG(total_amount) AS avg_order_value
    FROM {{ ref('stg_orders') }}
    WHERE order_date BETWEEN DATEADD(YEAR, -1, CURRENT_TIMESTAMP()) AND CURRENT_TIMESTAMP()
        AND status IN ('completed', 'shipped')
    GROUP BY region
    ORDER BY total_sales DESC
