-- dbt model generated from stored procedure: dbo.sp_GetCustomerById
-- Generated by Datarcon on 2026-03-10 17:24:55
-- Original procedure translated to databricks SQL


{{ config(
    materialized='view',
    schema='procedures'
) }}

SELECT customer_id, first_name, last_name, email, phone, created_at, updated_at
    FROM {{ ref('stg_customers') }}
    WHERE is_active = TRUE
