-- dbt model generated from stored procedure: dbo.sp_GetActiveProducts
-- Generated by Datarcon on 2026-03-10 17:24:55
-- Original procedure translated to databricks SQL


{{ config(
    materialized='view',
    schema='procedures'
) }}

SELECT product_id, name, sku, category, price, stock_quantity
    FROM {{ ref('stg_products') }}
    WHERE is_active = TRUE
    ORDER BY category, name
